# Generated by Django 4.2.4 on 2023-08-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='porfolio/images'),
        ),
    ]
